#!/usr/bin/env bash
# Materialise src/multiplayer/turn-config.js from .credentials (or
# the NEON_TURN_CONFIG env var if .credentials is absent — CI path).
#
# The generated file IS shipped to the browser (it has to be, the
# game runs static on GitHub Pages), so the credentials inside it
# are necessarily public. .credentials itself stays out of git via
# .gitignore — this keeps the values out of the SOURCE history,
# even though they end up in the deployed bundle. That's a
# reasonable boundary for a free-tier Metered project: rotate the
# API key + TURN creds if they ever land somewhere unintended.
#
# Usage:
#   ./tools/install-turn-config.sh
# CI usage (workflow sets NEON_TURN_CONFIG to the JSON from a
# GitHub Secret):
#   NEON_TURN_CONFIG="$(echo -n "$SECRET_JSON")" ./tools/install-turn-config.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/multiplayer/turn-config.js"
CRED_FILE="$ROOT/.credentials"

if [ -n "${NEON_TURN_CONFIG:-}" ]; then
    SRC_DESC="env NEON_TURN_CONFIG"
    JSON="$NEON_TURN_CONFIG"
elif [ -f "$CRED_FILE" ]; then
    SRC_DESC=".credentials"
    JSON="$(cat "$CRED_FILE")"
else
    echo "install-turn-config: no .credentials and no NEON_TURN_CONFIG;"
    echo "  generating EMPTY turn-config.js (STUN-only fallback)."
    cat > "$OUT" <<'EOF'
// turn-config.js — auto-generated by tools/install-turn-config.sh
// EMPTY bundle: no .credentials and no NEON_TURN_CONFIG were available
// when this was generated. WebRTC will fall back to public STUN only;
// peers behind symmetric NAT may not connect.
(function () {
    if (typeof window !== 'undefined') {
        window.__neonTurnConfig = { iceServers: [], generated: 'empty' };
    }
})();
EOF
    exit 0
fi

# Extract the staticIceServers array as a JS literal. node is the
# safest JSON → JS literal printer; we already require it for tests.
node -e "
const raw = process.argv[1];
const cfg = JSON.parse(raw);
const ice = (cfg.metered && cfg.metered.staticIceServers) || [];
process.stdout.write(JSON.stringify(ice, null, 2));
" "$JSON" > /tmp/neon-ice-$$.json

cat > "$OUT" <<EOF
// turn-config.js — auto-generated by tools/install-turn-config.sh
// Source: $SRC_DESC (NOT in git). Regenerated on every deploy.
// These ICE servers ride in window.__neonTurnConfig and get passed
// to Trystero's RTCPeerConnection via rtcConfig so peers behind
// symmetric NAT can relay through TURN when STUN isn't enough.
(function () {
    if (typeof window === 'undefined') return;
    window.__neonTurnConfig = {
        iceServers: $(cat /tmp/neon-ice-$$.json),
        generated: '$SRC_DESC',
    };
})();
EOF

rm -f /tmp/neon-ice-$$.json
echo "install-turn-config: wrote $OUT from $SRC_DESC"
