#!/usr/bin/env bash
# Materialise two browser-side config bundles from .credentials (local
# dev) or the NEON_TURN_CONFIG env var (CI deploy). Both bundles are
# gitignored — they regenerate on every build:
#
#   src/multiplayer/turn-config.js
#     window.__neonTurnConfig.iceServers  (Metered TURN+STUN list)
#
#   src/multiplayer/mqtt-config.js
#     window.__neonMqttRelayUrls          (one URL with embedded
#                                          URL-encoded basic auth for
#                                          the HiveMQ Cloud cluster)
#
# Reality check: a static page with NO backend can't hide secrets from
# its own users. The deployed JS bundle inevitably contains both. The
# enforced boundary is "no credentials in git source history" — the
# bundle gets rebuilt per-deploy from a GitHub Secret. If the keys
# leak somewhere unintended, rotate via the Metered / HiveMQ dashboards
# and the next push picks up the new values.
#
# To reduce blast radius on HiveMQ: configure an ACL on the cluster's
# "neon-defense" user so it can only publish/subscribe under the
# topic prefix matching our appId (`neon-defense-v1/#`). Random visitors
# with devtools can then participate in Neon Defense rooms but can't
# use the cluster for other traffic.
#
# Usage (local dev):
#   ./tools/install-turn-config.sh
#
# Usage (CI):
#   NEON_TURN_CONFIG="$(cat .credentials)" ./tools/install-turn-config.sh
# (The GitHub Secret named NEON_TURN_CONFIG holds the same JSON.)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TURN_OUT="$ROOT/src/multiplayer/turn-config.js"
MQTT_OUT="$ROOT/src/multiplayer/mqtt-config.js"
CRED_FILE="$ROOT/.credentials"

emit_empty() {
    cat > "$TURN_OUT" <<'EOF'
// turn-config.js — auto-generated; EMPTY (no .credentials, no secret).
(function () {
    if (typeof window !== 'undefined') {
        window.__neonTurnConfig = { iceServers: [], generated: 'empty' };
    }
})();
EOF
    cat > "$MQTT_OUT" <<'EOF'
// mqtt-config.js — auto-generated; EMPTY (no .credentials, no secret).
// transport-trystero.js will fall back to the public EMQX broker.
(function () {
    if (typeof window !== 'undefined') {
        window.__neonMqttRelayUrls = null;
    }
})();
EOF
}

if [ -n "${NEON_TURN_CONFIG:-}" ]; then
    SRC_DESC="env NEON_TURN_CONFIG"
    JSON="$NEON_TURN_CONFIG"
elif [ -f "$CRED_FILE" ]; then
    SRC_DESC=".credentials"
    JSON="$(cat "$CRED_FILE")"
else
    echo "install: no .credentials and no NEON_TURN_CONFIG;"
    echo "  emitting EMPTY bundles (STUN-only + public EMQX fallback)."
    emit_empty
    exit 0
fi

# Use node to safely produce the JS literals + URL-encode the HiveMQ
# password. node is already a dev-time dep (test runner uses it).
node -e "
const cfg = JSON.parse(process.argv[1]);
const ice = (cfg.metered && cfg.metered.staticIceServers) || [];
const hm  = cfg.hivemq || null;
let mqttUrls = null;
if (hm && hm.host && hm.username && hm.password) {
    const u = encodeURIComponent(hm.username);
    const p = encodeURIComponent(hm.password);
    const port = hm.wssPort || 8884;
    const path = hm.wssPath || '/mqtt';
    // wss://USER:PASS@HOST:PORT/PATH — mqtt.js inside Trystero parses
    // basic-auth out of the URL automatically. URL-encoded so special
    // chars in the password (#, *, @, etc.) don't break the parse.
    mqttUrls = ['wss://' + u + ':' + p + '@' + hm.host + ':' + port + path];
}
process.stdout.write(JSON.stringify({ ice, mqttUrls }, null, 2));
" "$JSON" > /tmp/neon-bundle-$$.json

ICE_JSON="$(node -e "console.log(JSON.stringify(JSON.parse(require('fs').readFileSync('/tmp/neon-bundle-$$.json','utf8')).ice, null, 2))")"
MQTT_JSON="$(node -e "console.log(JSON.stringify(JSON.parse(require('fs').readFileSync('/tmp/neon-bundle-$$.json','utf8')).mqttUrls))")"

cat > "$TURN_OUT" <<EOF
// turn-config.js — auto-generated by tools/install-turn-config.sh
// Source: $SRC_DESC (NOT in git). Regenerated on every deploy.
(function () {
    if (typeof window === 'undefined') return;
    window.__neonTurnConfig = {
        iceServers: $ICE_JSON,
        generated: '$SRC_DESC',
    };
})();
EOF

cat > "$MQTT_OUT" <<EOF
// mqtt-config.js — auto-generated by tools/install-turn-config.sh
// Source: $SRC_DESC (NOT in git). Regenerated on every deploy.
// When non-null, transport-trystero.js uses these URLs as the
// Trystero MQTT relay list (overrides the public EMQX default).
// URL-embedded basic auth is URL-encoded.
(function () {
    if (typeof window === 'undefined') return;
    window.__neonMqttRelayUrls = $MQTT_JSON;
})();
EOF

rm -f /tmp/neon-bundle-$$.json
echo "install: wrote $TURN_OUT + $MQTT_OUT from $SRC_DESC"
